"""Publish a feature clip and print the URL that embeds it in a PR.

Clips live on an orphan ``demo-media`` branch, one per repo, at
``clips/<branch>/<slug>.gif``. Three properties make that the right home:

- Every yeaboi repo is public, so ``raw.githubusercontent.com`` renders the GIF
  inline in PR markdown. No CDN, no upload API, no second PR to merge first.
- An orphan branch shares no history with ``main``, so a binary that changes on
  every re-record never weighs on a clone of the code.
- The path is keyed on the **branch**, not the PR number, so this works before
  the PR exists and updates in place after it does.

Everything goes through the GitHub API — nothing checks the media branch out,
because the working tree here is usually somebody's feature worktree.

    python scripts/clip_publish.py .demo/out/my-feature.gif
    python scripts/clip_publish.py .demo/out/my-feature.gif --markdown
"""

from __future__ import annotations

import argparse
import base64
import json
import logging
import re
import subprocess
import sys
from pathlib import Path

logger = logging.getLogger("clip-publish")

MEDIA_BRANCH = "demo-media"
RAW = "https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{path}"

# GitHub renders an inline image up to a point; past it the PR just shows a
# broken frame. The recorder's own ceiling is 6MB, so this only catches a clip
# published without going through `make clip`.
MAX_BYTES = 6 * 1024 * 1024


def gh(*args: str, stdin: str | None = None, check: bool = True) -> tuple[int, str]:
    proc = subprocess.run(
        ["gh", *args],
        input=stdin,
        capture_output=True,
        text=True,
    )
    if check and proc.returncode != 0:
        sys.exit(f"gh {' '.join(args)} failed:\n{proc.stderr.strip()}")
    return proc.returncode, proc.stdout.strip()


def repo_slug() -> tuple[str, str]:
    _, out = gh("repo", "view", "--json", "owner,name")
    data = json.loads(out)
    return data["owner"]["login"], data["name"]


def current_branch() -> str:
    out = subprocess.run(["git", "branch", "--show-current"], capture_output=True, text=True, check=True).stdout.strip()
    if not out:
        sys.exit("detached HEAD — a clip is published under a branch name")
    return out


def slugify(name: str) -> str:
    """A path segment safe for a URL, from a branch name or a filename."""
    return re.sub(r"[^a-zA-Z0-9._/-]+", "-", name).strip("-")


def ensure_media_branch(owner: str, repo: str) -> None:
    """Create the orphan branch on first publish.

    Built through the git data API rather than a local checkout: a commit with
    no parents is what makes it an orphan, and `gh api` is the only way to push
    one without switching branches in the caller's working tree.
    """
    code, _ = gh("api", f"repos/{owner}/{repo}/branches/{MEDIA_BRANCH}", check=False)
    if code == 0:
        return
    logger.info("creating the orphan %s branch (first publish for this repo)", MEDIA_BRANCH)

    readme = (
        f"# {repo} — feature clips\n\n"
        "Recordings attached to pull requests, one directory per branch.\n"
        "Generated by `make clip` + `clip_publish.py`; no source lives here, and\n"
        "this branch deliberately shares no history with `main`.\n"
    )
    _, blob = gh(
        "api",
        "-X",
        "POST",
        f"repos/{owner}/{repo}/git/blobs",
        "--input",
        "-",
        stdin=json.dumps({"content": base64.b64encode(readme.encode()).decode(), "encoding": "base64"}),
    )
    blob_sha = json.loads(blob)["sha"]

    _, tree = gh(
        "api",
        "-X",
        "POST",
        f"repos/{owner}/{repo}/git/trees",
        "--input",
        "-",
        stdin=json.dumps({"tree": [{"path": "README.md", "mode": "100644", "type": "blob", "sha": blob_sha}]}),
    )
    tree_sha = json.loads(tree)["sha"]

    _, commit = gh(
        "api",
        "-X",
        "POST",
        f"repos/{owner}/{repo}/git/commits",
        "--input",
        "-",
        stdin=json.dumps({"message": "start the feature-clip media branch", "tree": tree_sha, "parents": []}),
    )
    commit_sha = json.loads(commit)["sha"]

    gh(
        "api",
        "-X",
        "POST",
        f"repos/{owner}/{repo}/git/refs",
        "--input",
        "-",
        stdin=json.dumps({"ref": f"refs/heads/{MEDIA_BRANCH}", "sha": commit_sha}),
    )


def publish(gif: Path, branch: str | None = None) -> str:
    if not gif.is_file():
        sys.exit(f"no such clip: {gif} — run `make clip SPEC=…` first")
    size = gif.stat().st_size
    if size > MAX_BYTES:
        sys.exit(f"{gif} is {size} bytes (limit {MAX_BYTES}) — GitHub will not render it inline")

    owner, repo = repo_slug()
    ensure_media_branch(owner, repo)
    path = f"clips/{slugify(branch or current_branch())}/{slugify(gif.name)}"

    # Overwrite in place when this clip was published before, so re-recording
    # updates the image already embedded in the PR instead of orphaning it.
    code, existing = gh("api", f"repos/{owner}/{repo}/contents/{path}?ref={MEDIA_BRANCH}", "--jq", ".sha", check=False)
    payload = {
        "message": f"clip: {gif.stem}",
        "branch": MEDIA_BRANCH,
        "content": base64.b64encode(gif.read_bytes()).decode(),
    }
    if code == 0 and existing:
        payload["sha"] = existing

    gh("api", "-X", "PUT", f"repos/{owner}/{repo}/contents/{path}", "--input", "-", stdin=json.dumps(payload))
    return RAW.format(owner=owner, repo=repo, branch=MEDIA_BRANCH, path=path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Publish a feature clip and print its URL.")
    parser.add_argument("gif", type=Path)
    parser.add_argument("--branch", default=None, help="override the branch the clip is filed under")
    parser.add_argument("--markdown", action="store_true", help="print a ready-to-paste `## Demo` section")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="[clip-publish] %(message)s")
    url = publish(args.gif, args.branch)
    if args.markdown:
        print(f"## Demo\n\n![{args.gif.stem}]({url})")
    else:
        print(url)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
